package com.cainiao1053.cbcmoreshells.index;

import com.cainiao1053.cbcmoreshells.Cbcmoreshells;
import com.cainiao1053.cbcmoreshells.cannons.dual_cannon.material.DualCannonMaterial;
import com.cainiao1053.cbcmoreshells.cannons.dual_cannon.material.DualCannonMaterialProperties;


public class CBCMSDualCannonMaterials {

    public static final DualCannonMaterial

            CAST_IRON = DualCannonMaterial.register(Cbcmoreshells.resource("cast_iron"),
            DualCannonMaterialProperties.builder()
                    .minimumVelocityPerBarrel(2d)
                    .weight(1.0f)
                    .maxSafePropellantStress(2)
                    .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                    .connectsInSurvival(true)
                    .isWeldable(true)
                    .weldDamage(1)
                    .weldStressPenalty(1)
                    .minimumSpread(2.6f)
                    .spreadReductionPerBarrel(2.5f)
                    .addedLifetime(5)
                    .reloadTimeModifier(0.7f)
                    .durabilityMassModifier(0.59f)
                    .barrelGap(0.5f)
                    .combatCommandCooldown(1800)
                    .combatCommandDuration(400)
                    .isSingleBarrel(false)
                    .build()),
            WIDE_SINGLE_CAST_IRON = DualCannonMaterial.register(Cbcmoreshells.resource("wide_single_cast_iron"),
                    DualCannonMaterialProperties.builder()
                            .minimumVelocityPerBarrel(1d)
                            .weight(1.0f)
                            .maxSafePropellantStress(10)
                            .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                            .connectsInSurvival(true)
                            .isWeldable(true)
                            .weldDamage(0)
                            .weldStressPenalty(0)
                            .minimumSpread(2.7f)
                            .spreadReductionPerBarrel(2.5f)
                            .addedLifetime(15)
                            .reloadTimeModifier(1.4f)
                            .durabilityMassModifier(0.92f)
                            .barrelGap(0f)
                            .combatCommandCooldown(1800)
                            .combatCommandDuration(400)
                            .isSingleBarrel(true)
                            .build()),

            BRONZE = DualCannonMaterial.register(Cbcmoreshells.resource("bronze"),
                    DualCannonMaterialProperties.builder()
                            .minimumVelocityPerBarrel(4d / 3d)
                            .weight(2.0f)
                            .maxSafePropellantStress(4)
                            .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                            .connectsInSurvival(true)
                            .isWeldable(true)
                            .weldDamage(0)
                            .weldStressPenalty(0)
                            .minimumSpread(2.2f)
                            .spreadReductionPerBarrel(2.5f)
                            .addedLifetime(20)
                            .reloadTimeModifier(0.8f)
                            .durabilityMassModifier(0.72f)
                            .barrelGap(0.5f)
                            .combatCommandCooldown(1800)
                            .combatCommandDuration(400)
                            .isSingleBarrel(false)
                            .build()),
            WIDE_SINGLE_BRONZE = DualCannonMaterial.register(Cbcmoreshells.resource("wide_single_bronze"),
                    DualCannonMaterialProperties.builder()
                            .minimumVelocityPerBarrel(4d / 3d)
                            .weight(2.0f)
                            .maxSafePropellantStress(4)
                            .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                            .connectsInSurvival(true)
                            .isWeldable(true)
                            .weldDamage(0)
                            .weldStressPenalty(0)
                            .minimumSpread(2.1f)
                            .spreadReductionPerBarrel(2.5f)
                            .addedLifetime(30)
                            .reloadTimeModifier(1.5f)
                            .durabilityMassModifier(1.15f)
                            .barrelGap(0f)
                            .combatCommandCooldown(1800)
                            .combatCommandDuration(400)
                            .isSingleBarrel(true)
                            .build()),


            BRASS = DualCannonMaterial.register(Cbcmoreshells.resource("brass"),
                    DualCannonMaterialProperties.builder()
                            .minimumVelocityPerBarrel(4d / 3d)
                            .weight(4.0f)
                            .maxSafePropellantStress(10)
                            .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                            .connectsInSurvival(true)
                            .isWeldable(true)
                            .weldDamage(0)
                            .weldStressPenalty(0)
                            .minimumSpread(1.8f)
                            .spreadReductionPerBarrel(2.5f)
                            .addedLifetime(30)
                            .reloadTimeModifier(0.7f)
                            .durabilityMassModifier(0.75f)
                            .barrelGap(0.5f)
                            .combatCommandCooldown(2400)
                            .combatCommandDuration(600)
                            .isSingleBarrel(false)
                            .build()),

            STEEL = DualCannonMaterial.register(Cbcmoreshells.resource("steel"),
                    DualCannonMaterialProperties.builder()
                            .minimumVelocityPerBarrel(1d)
                            .weight(4.0f)
                            .maxSafePropellantStress(10)
                            .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                            .connectsInSurvival(true)
                            .isWeldable(true)
                            .weldDamage(0)
                            .weldStressPenalty(0)
                            .minimumSpread(1.3f)
                            .spreadReductionPerBarrel(2.5f)
                            .addedLifetime(50)
                            .reloadTimeModifier(1f)
                            .durabilityMassModifier(0.9f)
                            .barrelGap(0.5f)
                            .combatCommandCooldown(1800)
                            .combatCommandDuration(500)
                            .isSingleBarrel(false)
                            .build()),
            SINGLE_STEEL = DualCannonMaterial.register(Cbcmoreshells.resource("single_steel"),
                    DualCannonMaterialProperties.builder()
                            .minimumVelocityPerBarrel(1d)
                            .weight(4.0f)
                            .maxSafePropellantStress(10)
                            .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                            .connectsInSurvival(true)
                            .isWeldable(true)
                            .weldDamage(0)
                            .weldStressPenalty(0)
                            .minimumSpread(1.4f)
                            .spreadReductionPerBarrel(2.5f)
                            .addedLifetime(50)
                            .reloadTimeModifier(0.92f)
                            .durabilityMassModifier(0.9f)
                            .barrelGap(0f)
                            .combatCommandCooldown(1800)
                            .combatCommandDuration(500)
                            .isSingleBarrel(true)
                            .build()),
                    SLATE_ALLOY = DualCannonMaterial.register(Cbcmoreshells.resource("slate_alloy"),
                            DualCannonMaterialProperties.builder()
                                    .minimumVelocityPerBarrel(1d)
                                    .weight(4.0f)
                                    .maxSafePropellantStress(10)
                                    .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                                    .connectsInSurvival(true)
                                    .isWeldable(true)
                                    .weldDamage(0)
                                    .weldStressPenalty(0)
                                    .minimumSpread(1.4f)
                                    .spreadReductionPerBarrel(2.5f)
                                    .addedLifetime(60)
                                    .reloadTimeModifier(1.2f)
                                    .durabilityMassModifier(1.05f)
                                    .barrelGap(0.5f)
                                    .combatCommandCooldown(2400)
                                    .combatCommandDuration(700)
                                    .isSingleBarrel(false)
                                    .build()),

            TOUGH_STEEL = DualCannonMaterial.register(Cbcmoreshells.resource("tough_steel"),
                    DualCannonMaterialProperties.builder()
                            .minimumVelocityPerBarrel(1d)
                            .weight(4.0f)
                            .maxSafePropellantStress(10)
                            .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                            .connectsInSurvival(true)
                            .isWeldable(true)
                            .weldDamage(0)
                            .weldStressPenalty(0)
                            .minimumSpread(1.45f)
                            .spreadReductionPerBarrel(2.5f)
                            .addedLifetime(50)
                            .reloadTimeModifier(1.35f)
                            .durabilityMassModifier(1.2f)
                            .barrelGap(0.5f)
                            .combatCommandCooldown(1800)
                            .combatCommandDuration(400)
                            .isSingleBarrel(false)
                            .build()),

            ROSEQUARTZ_BRASS = DualCannonMaterial.register(Cbcmoreshells.resource("rosequartz_brass"),
                    DualCannonMaterialProperties.builder()
                            .minimumVelocityPerBarrel(1d)
                            .weight(4.0f)
                            .maxSafePropellantStress(10)
                            .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                            .connectsInSurvival(true)
                            .isWeldable(true)
                            .weldDamage(0)
                            .weldStressPenalty(0)
                            .minimumSpread(1.55f)
                            .spreadReductionPerBarrel(2.5f)
                            .addedLifetime(40)
                            .reloadTimeModifier(1.15f)
                            .durabilityMassModifier(0.84f)
                            .barrelGap(0.5f)
                            .combatCommandCooldown(3600)
                            .combatCommandDuration(1800)
                            .isSingleBarrel(false)
                            .build()),

            NETHER_STEEL = DualCannonMaterial.register(Cbcmoreshells.resource("nether_steel"),
                    DualCannonMaterialProperties.builder()
                            .minimumVelocityPerBarrel(1d)
                            .weight(6.0f)
                            .maxSafePropellantStress(10)
                            .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                            .connectsInSurvival(true)
                            .isWeldable(true)
                            .weldDamage(0)
                            .weldStressPenalty(0)
                            .minimumSpread(0.35f)
                            .spreadReductionPerBarrel(2.5f)
                            .addedLifetime(90)
                            .reloadTimeModifier(1.3f)
                            .durabilityMassModifier(1f)
                            .barrelGap(0.5f)
                            .combatCommandCooldown(1800)
                            .combatCommandDuration(400)
                            .isSingleBarrel(false)
                            .build()),
            WIDE_STEEL = DualCannonMaterial.register(Cbcmoreshells.resource("wide_steel"),
                    DualCannonMaterialProperties.builder()
                            .minimumVelocityPerBarrel(1d)
                            .weight(3.0f)
                            .maxSafePropellantStress(10)
                            .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                            .connectsInSurvival(true)
                            .isWeldable(true)
                            .weldDamage(0)
                            .weldStressPenalty(0)
                            .minimumSpread(1.1f)
                            .spreadReductionPerBarrel(2.5f)
                            .addedLifetime(85)
                            .reloadTimeModifier(1.72f)
                            .durabilityMassModifier(1.45f)
                            .barrelGap(1f)
                            .combatCommandCooldown(1800)
                            .combatCommandDuration(500)
                            .isSingleBarrel(false)
                            .build()),
            WIDE_BRASS = DualCannonMaterial.register(Cbcmoreshells.resource("wide_brass"),
                    DualCannonMaterialProperties.builder()
                            .minimumVelocityPerBarrel(4d / 3d)
                            .weight(4.0f)
                            .maxSafePropellantStress(10)
                            .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                            .connectsInSurvival(true)
                            .isWeldable(true)
                            .weldDamage(0)
                            .weldStressPenalty(0)
                            .minimumSpread(1.6f)
                            .spreadReductionPerBarrel(2.5f)
                            .addedLifetime(65)
                            .reloadTimeModifier(1.44f)
                            .durabilityMassModifier(1.3f)
                            .barrelGap(1f)
                            .combatCommandCooldown(1800)
                            .combatCommandDuration(600)
                            .isSingleBarrel(false)
                            .build()),
            WIDE_NETHER_STEEL = DualCannonMaterial.register(Cbcmoreshells.resource("wide_nether_steel"),
                    DualCannonMaterialProperties.builder()
                            .minimumVelocityPerBarrel(1d)
                            .weight(8.0f)
                            .maxSafePropellantStress(10)
                            .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                            .connectsInSurvival(true)
                            .isWeldable(true)
                            .weldDamage(0)
                            .weldStressPenalty(0)
                            .minimumSpread(0.35f)
                            .spreadReductionPerBarrel(2.5f)
                            .addedLifetime(140)
                            .reloadTimeModifier(1.9f)
                            .durabilityMassModifier(1.4f)
                            .barrelGap(1f)
                            .combatCommandCooldown(1800)
                            .combatCommandDuration(500)
                            .isSingleBarrel(false)
                            .build()),
            WIDE_TOUGH_STEEL = DualCannonMaterial.register(Cbcmoreshells.resource("wide_tough_steel"),
                    DualCannonMaterialProperties.builder()
                            .minimumVelocityPerBarrel(1d)
                            .weight(4.0f)
                            .maxSafePropellantStress(10)
                            .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                            .connectsInSurvival(true)
                            .isWeldable(true)
                            .weldDamage(0)
                            .weldStressPenalty(0)
                            .minimumSpread(1.65f)
                            .spreadReductionPerBarrel(2.5f)
                            .addedLifetime(70)
                            .reloadTimeModifier(2.9f)
                            .durabilityMassModifier(1.92f)
                            .barrelGap(1f)
                            .combatCommandCooldown(1200)
                            .combatCommandDuration(200)
                            .isSingleBarrel(false)
                            .build()),
                    WIDE_SLATE_ALLOY = DualCannonMaterial.register(Cbcmoreshells.resource("wide_slate_alloy"),
                            DualCannonMaterialProperties.builder()
                                    .minimumVelocityPerBarrel(1d)
                                    .weight(3.0f)
                                    .maxSafePropellantStress(10)
                                    .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                                    .connectsInSurvival(true)
                                    .isWeldable(true)
                                    .weldDamage(0)
                                    .weldStressPenalty(0)
                                    .minimumSpread(1.3f)
                                    .spreadReductionPerBarrel(2.5f)
                                    .addedLifetime(110)
                                    .reloadTimeModifier(2.2f)
                                    .durabilityMassModifier(1.7f)
                                    .barrelGap(1f)
                                    .combatCommandCooldown(2400)
                                    .combatCommandDuration(700)
                                    .isSingleBarrel(false)
                                    .build()),

            WIDE_ROSEQUARTZ_BRASS = DualCannonMaterial.register(Cbcmoreshells.resource("wide_rosequartz_brass"),
                    DualCannonMaterialProperties.builder()
                            .minimumVelocityPerBarrel(1d)
                            .weight(4.0f)
                            .maxSafePropellantStress(10)
                            .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                            .connectsInSurvival(true)
                            .isWeldable(true)
                            .weldDamage(0)
                            .weldStressPenalty(0)
                            .minimumSpread(1.6f)
                            .spreadReductionPerBarrel(2.5f)
                            .addedLifetime(70)
                            .reloadTimeModifier(1.75f)
                            .durabilityMassModifier(1.25f)
                            .barrelGap(1f)
                            .combatCommandCooldown(3600)
                            .combatCommandDuration(1800)
                            .isSingleBarrel(false)
                            .build()),

            PODIA_ZINC = DualCannonMaterial.register(Cbcmoreshells.resource("podia_zinc"),
                    DualCannonMaterialProperties.builder()
                            .minimumVelocityPerBarrel(4d / 3d)
                            .weight(4.0f)
                            .maxSafePropellantStress(10)
                            .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                            .connectsInSurvival(true)
                            .isWeldable(true)
                            .weldDamage(0)
                            .weldStressPenalty(0)
                            .minimumSpread(1.9f)
                            .spreadReductionPerBarrel(2.5f)
                            .addedLifetime(30)
                            .reloadTimeModifier(0.8f)
                            .durabilityMassModifier(0.75f)
                            .barrelGap(0.5f)
                            .combatCommandCooldown(1200)
                            .combatCommandDuration(600)
                            .isSingleBarrel(false)
                            .build()),

            STARLIGHT_INGOT = DualCannonMaterial.register(Cbcmoreshells.resource("starlight_ingot"),
                    DualCannonMaterialProperties.builder()
                            .minimumVelocityPerBarrel(4d / 3d)
                            .weight(4.0f)
                            .maxSafePropellantStress(10)
                            .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                            .connectsInSurvival(true)
                            .isWeldable(true)
                            .weldDamage(0)
                            .weldStressPenalty(0)
                            .minimumSpread(2.1f)
                            .spreadReductionPerBarrel(2.5f)
                            .addedLifetime(20)
                            .reloadTimeModifier(0.84f)
                            .durabilityMassModifier(0.72f)
                            .barrelGap(0.5f)
                            .combatCommandCooldown(1800)
                            .combatCommandDuration(1200)
                            .isSingleBarrel(false)
                            .build()),

            HAMLET_STEEL = DualCannonMaterial.register(Cbcmoreshells.resource("hamlet_steel"),
                    DualCannonMaterialProperties.builder()
                            .minimumVelocityPerBarrel(1d)
                            .weight(6.0f)
                            .maxSafePropellantStress(10)
                            .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                            .connectsInSurvival(true)
                            .isWeldable(true)
                            .weldDamage(0)
                            .weldStressPenalty(0)
                            .minimumSpread(0.75f)
                            .spreadReductionPerBarrel(2.5f)
                            .addedLifetime(90)
                            .reloadTimeModifier(1.28f)
                            .durabilityMassModifier(0.93f)
                            .barrelGap(0.5f)
                            .combatCommandCooldown(2400)
                            .combatCommandDuration(600)
                            .isSingleBarrel(false)
                            .build()),
            WIDE_SINGLE_STEEL = DualCannonMaterial.register(Cbcmoreshells.resource("wide_single_steel"),
                    DualCannonMaterialProperties.builder()
                            .minimumVelocityPerBarrel(1d)
                            .weight(3.0f)
                            .maxSafePropellantStress(10)
                            .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                            .connectsInSurvival(true)
                            .isWeldable(true)
                            .weldDamage(0)
                            .weldStressPenalty(0)
                            .minimumSpread(1.3f)
                            .spreadReductionPerBarrel(2.5f)
                            .addedLifetime(85)
                            .reloadTimeModifier(1.6f)
                            .durabilityMassModifier(1.45f)
                            .barrelGap(0f)
                            .combatCommandCooldown(1800)
                            .combatCommandDuration(500)
                            .isSingleBarrel(true)
                            .build()),
            WIDE_SINGLE_TOUGH_STEEL = DualCannonMaterial.register(Cbcmoreshells.resource("wide_single_tough_steel"),
                    DualCannonMaterialProperties.builder()
                            .minimumVelocityPerBarrel(1d)
                            .weight(4.0f)
                            .maxSafePropellantStress(10)
                            .failureMode(DualCannonMaterialProperties.FailureMode.RUPTURE)
                            .connectsInSurvival(true)
                            .isWeldable(true)
                            .weldDamage(0)
                            .weldStressPenalty(0)
                            .minimumSpread(1.55f)
                            .spreadReductionPerBarrel(2.5f)
                            .addedLifetime(70)
                            .reloadTimeModifier(2.7f)
                            .durabilityMassModifier(1.92f)
                            .barrelGap(0f)
                            .combatCommandCooldown(2400)
                            .combatCommandDuration(600)
                            .isSingleBarrel(true)
                            .build());


}
